sudo: required
services:
  - docker
before_install:
  - docker build -t arupsarkar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arupsarkar/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-045319707867"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: "$AWS_ACCESS_ID"
    secret_access_key:
      secure: "$AWS_ACCESS_KEY"